# Generated by Django 5.0 on 2023-12-24 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='code',
            name='name',
            field=models.CharField(default='UNKNOWN', max_length=255),
        ),
    ]
