# Generated by Django 5.0 on 2023-12-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_code_created_at_code_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
